# action.yml
name: 'powerbi-actions'

description: 'Automate common deployment tasks related to PowerBI'

inputs:
  AuthenticationType: # Authentication type
    description: 'Select the action you would like to perform'
    required: true
    default: 'User'
  userName: # Username
    description: 'The username of the user that will perform the actions'
    required: true
  passWord: # Password
    description: 'The password of the user'
    required: true
  clientId: # Client ID
    description: 'The client id of the Azure Active Directory application'
    required: true
  clientSecret: # Client Secret
    description: 'The client secret of the application'
    required: true
  tenantId: # Tenant ID
    description: 'The identifier of the Azure Active Directory tenant'
    required: true
  
runs:
  using: 'docker'
  image: 'Dockerfile'
