name: CI-NoAction
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Call the PS script and pu lish PBI contents
        shell: pwsh
        run: |
          . GitHub/run-task.ps1 -ClientId ${{ secrets.CLIENTID }} -Secret ${{ secrets.CLIENTSECRET }} -TenantId ${{ secrets.TENANTID }} -WorkspaceName "Training"
